name: PR WorkFlow

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build setup task
      run: ./gradlew init
    - name: Build with Gradle and test
      run: ./gradlew build
    - name: Execute jar
      run: sudo kill -9 `sudo lsof -t -i:80` & sudo java -jar /root/actions-runner/_work/Drones/Drones/build/libs/the-drone-0.0.1-SNAPSHOT.jar &