name: PR WorkFlow

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Test
      run: ./gradlew test
    - name: Clean
      run: ./gradlew clean
    - name: Create runnable fat jar
      run: ./gradlew bootJar
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: build/libs/the-drone-0.0.1-SNAPSHOT.jar
    
  deploy:
    needs: tests
    name: Deploy
    runs-on: ubuntu-latest
    steps:
       - name: Download and Deploy JAR
        uses: actions/download-artifact@v3
        with:
          name: artifact
      - name: Display structure of downloaded files
        run: ls -R
      - name: SCP file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          rm: true
          source: the-drone-0.0.1-SNAPSHOT.jar
          target: "scp/artifacts"
      
