name: PUSH Workflow
on:
  push:
    branches:
      - main

permissions:
  contents: read
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Test
      run: ./gradlew test
 
  deploy:
    needs: tests
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        run: ./gradlew clean
      - name: Create runnable fat jar
        run: ./gradlew bootJar
      - name: SCP file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          rm: true
          source: "build/libs/the-drone-0.0.1-SNAPSHOT.jar"
          target: "scp/the-drone.jar"
      