name: PUSH Workflow
on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    #Run Tests
    - name: Run Tests
      run: ./gradlew test
    - name: Execute jar
      run: sudo kill -9 `sudo lsof -t -i:80` & sudo java -jar /root/actions-runner/_work/Drones/Drones/build/libs/the-drone-0.0.1-SNAPSHOT.jar &
