name: PUSH Workflow
on:
  push:
    branches:
      - main

permissions:
  contents: read
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Test
      run: ./gradlew test
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: build/libs/the-drone-0.0.1-SNAPSHOT.jar
    # - name: Execute jar
    #   run: sudo kill -9 `sudo lsof -t -i:80` & sudo java -jar /root/actions-runner/_work/Drones/Drones/build/libs/the-drone-0.0.1-SNAPSHOT.jar &
  deploy:
    needs: tests
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Download and Deploy JAR
        uses: actions/download-artifact@v3
        with:
          name: artifact
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            mkdir drone && cd drone && mv artifact the-drone.jar